[2024-12-07T19:16:12.251+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-07T19:16:12.263+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: medal_count_dag.pick_medal_task manual__2024-12-07T19:16:06.569868+00:00 [queued]>
[2024-12-07T19:16:12.269+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: medal_count_dag.pick_medal_task manual__2024-12-07T19:16:06.569868+00:00 [queued]>
[2024-12-07T19:16:12.270+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-07T19:16:12.280+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): pick_medal_task> on 2024-12-07 19:16:06.569868+00:00
[2024-12-07T19:16:12.286+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4487) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-07T19:16:12.288+0000] {standard_task_runner.py:72} INFO - Started process 4489 to run task
[2024-12-07T19:16:12.288+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'medal_count_dag', 'pick_medal_task', 'manual__2024-12-07T19:16:06.569868+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpig8lw0y7']
[2024-12-07T19:16:12.289+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask pick_medal_task
[2024-12-07T19:16:12.323+0000] {task_command.py:467} INFO - Running <TaskInstance: medal_count_dag.pick_medal_task manual__2024-12-07T19:16:06.569868+00:00 [running]> on host a693d8a2436c
[2024-12-07T19:16:12.523+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='medal_count_dag' AIRFLOW_CTX_TASK_ID='pick_medal_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-07T19:16:06.569868+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-07T19:16:06.569868+00:00'
[2024-12-07T19:16:12.524+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-07T19:16:12.525+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-07T19:16:12.526+0000] {logging_mixin.py:190} INFO - Current task name:pick_medal_task state:running start_date:2024-12-07 19:16:12.264108+00:00
[2024-12-07T19:16:12.526+0000] {logging_mixin.py:190} INFO - Dag name:medal_count_dag and current dag run status:running
[2024-12-07T19:16:12.527+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-07T19:16:12.528+0000] {baseoperator.py:416} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-12-07T19:16:12.528+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main.py", line 58, in check_medal_type
    if medal_type == 'Bronze':
       ^^^^^^^^^^
NameError: name 'medal_type' is not defined
[2024-12-07T19:16:12.546+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-07T19:16:12.546+0000] {logging_mixin.py:190} INFO - Task start:2024-12-07 19:16:12.264108+00:00 end:2024-12-07 19:16:12.545833+00:00 duration:0.281725
[2024-12-07T19:16:12.547+0000] {logging_mixin.py:190} INFO - Task:<Task(BranchPythonOperator): pick_medal_task> dag:<DAG: medal_count_dag> dagrun:<DagRun medal_count_dag @ 2024-12-07 19:16:06.569868+00:00: manual__2024-12-07T19:16:06.569868+00:00, state:running, queued_at: 2024-12-07 19:16:06.575120+00:00. externally triggered: True>
[2024-12-07T19:16:12.548+0000] {logging_mixin.py:190} INFO - Failure caused by name 'medal_type' is not defined
[2024-12-07T19:16:12.548+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=medal_count_dag, task_id=pick_medal_task, run_id=manual__2024-12-07T19:16:06.569868+00:00, execution_date=20241207T191606, start_date=20241207T191612, end_date=20241207T191612
[2024-12-07T19:16:12.559+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-07T19:16:12.559+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 19 for task pick_medal_task (name 'medal_type' is not defined; 4489)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main.py", line 58, in check_medal_type
    if medal_type == 'Bronze':
       ^^^^^^^^^^
NameError: name 'medal_type' is not defined
[2024-12-07T19:16:12.584+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-07T19:16:12.600+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-07T19:16:12.604+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
